[WIP]merged example into main project, not building
SamuelMarks/actix-diesel-auth-scaffold pull request #2
Opened 2019-02-06 08:30 UTC by rishflab

Add oauth functionality with r2d2 and diesel. 
Uses diesel ORM instead of raw sql queries.

2019-02-14 02:49 UTC, SamuelMarks commented on src/bin/auth.rs
> +////#[macro_use]
Remove this file rather than comment it out?

2019-02-14 02:53 UTC, SamuelMarks requested changes

2019-02-14 02:53 UTC, SamuelMarks commented on src/bin/r2d2_auth.rs
> +fn create_user((item, state): (Json<MyUser>, State<state::AppState>)) -> impl Future<Item = HttpResponse, Error = Error> {
Would be good to separate user and token creation to separate modules

2019-02-14 02:53 UTC, SamuelMarks commented on src/config.rs
> +pub const SECRET: &str = "secret";
Make this an environment variable, and unwrap it without a default specified for added security

2019-02-14 02:53 UTC, SamuelMarks commented on src/db.rs
> +use actix_web::*;
Separate user and token handling to their own distinct modules

2019-02-14 02:53 UTC, SamuelMarks commented on src/schema.rs
> +    users (id) {
Why did you add an `id` and remove the other attributes I had?

2019-02-25 02:41 UTC, SamuelMarks commented
@rishflab It's been 20 days since this PR opened, what's going on?

Just tried to build the `rishflab:oauth-r2d2` branch, and it doesn't build.

2019-02-25 02:46 UTC, rishflab commented
> @rishflab It's been 20 days since this PR opened, what's going on?
> 
> Just tried to build the `rishflab:oauth-r2d2` branch, and it doesn't build.

yeh I broke it with recent commits. I am currently working on the android scaffold to get it AST based codgen working with it. 
I will fix this pull request either later tonight or first thing tomorrow as soon as the android scaffold is working with codegen

2019-03-19 04:04 UTC, SamuelMarks requested changes

2019-03-19 04:04 UTC, SamuelMarks commented on src/user/schema.rs
>          id -> Text,
Remove the `id`

2019-03-19 04:04 UTC, SamuelMarks commented on src/auth/routes.rs
> +            Err(_) => Ok(HttpResponse::InternalServerError().into()),
RFC6749 define specific error codes, here is some inspiration from what I did 5 years ago: https://github.com/ng-bottle-libraries/oauth2-rfc6749/blob/master/rfc6749/oauth2_errors.py

2019-03-26 06:17 UTC, merged